/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileEditRouteImport } from './routes/profile-edit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as ConfirmemailRouteImport } from './routes/confirmemail'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as BuddiesRouteImport } from './routes/buddies'
import { Route as GodaddyRouteRouteImport } from './routes/godaddy/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InteresserIndexRouteImport } from './routes/interesser/index'
import { Route as GodaddyIndexRouteImport } from './routes/godaddy/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as StravaCallbackRouteImport } from './routes/strava/callback'
import { Route as InteresserSlugRouteImport } from './routes/interesser/$slug'
import { Route as GodaddyAnalyticsRouteImport } from './routes/godaddy/analytics'
import { Route as ChatBuddyIdRouteImport } from './routes/chat/$buddyId'
import { Route as BuddySlugRouteImport } from './routes/buddy/$slug'
import { Route as ApiGenerateUsersRouteImport } from './routes/api/generate-users'
import { Route as ApiGenerateRelationsRouteImport } from './routes/api/generate-relations'
import { Route as ApiGenerateInterestsRouteImport } from './routes/api/generate-interests'
import { Route as ActivitiesOpretRouteImport } from './routes/activities/opret'
import { Route as GodaddyUsersIndexRouteImport } from './routes/godaddy/users/index'
import { Route as GodaddyInterestsIndexRouteImport } from './routes/godaddy/interests/index'
import { Route as ActivitiesSlugIndexRouteImport } from './routes/activities/$slug/index'
import { Route as GodaddyUsersGenerateRouteImport } from './routes/godaddy/users/generate'
import { Route as GodaddyUsersCreateRouteImport } from './routes/godaddy/users/create'
import { Route as GodaddyInterestsRelationsRouteImport } from './routes/godaddy/interests/relations'
import { Route as GodaddyInterestsGenerateRouteImport } from './routes/godaddy/interests/generate'
import { Route as GodaddyInterestsCreateRouteImport } from './routes/godaddy/interests/create'
import { Route as ActivitiesSlugRedigerRouteImport } from './routes/activities/$slug/rediger'
import { Route as GodaddyUsersUserIdEditRouteImport } from './routes/godaddy/users/$userId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile-edit',
  path: '/profile-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmemailRoute = ConfirmemailRouteImport.update({
  id: '/confirmemail',
  path: '/confirmemail',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddiesRoute = BuddiesRouteImport.update({
  id: '/buddies',
  path: '/buddies',
  getParentRoute: () => rootRouteImport,
} as any)
const GodaddyRouteRoute = GodaddyRouteRouteImport.update({
  id: '/godaddy',
  path: '/godaddy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteresserIndexRoute = InteresserIndexRouteImport.update({
  id: '/interesser/',
  path: '/interesser/',
  getParentRoute: () => rootRouteImport,
} as any)
const GodaddyIndexRoute = GodaddyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InteresserSlugRoute = InteresserSlugRouteImport.update({
  id: '/interesser/$slug',
  path: '/interesser/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GodaddyAnalyticsRoute = GodaddyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const ChatBuddyIdRoute = ChatBuddyIdRouteImport.update({
  id: '/chat/$buddyId',
  path: '/chat/$buddyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddySlugRoute = BuddySlugRouteImport.update({
  id: '/buddy/$slug',
  path: '/buddy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateUsersRoute = ApiGenerateUsersRouteImport.update({
  id: '/api/generate-users',
  path: '/api/generate-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRelationsRoute = ApiGenerateRelationsRouteImport.update({
  id: '/api/generate-relations',
  path: '/api/generate-relations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateInterestsRoute = ApiGenerateInterestsRouteImport.update({
  id: '/api/generate-interests',
  path: '/api/generate-interests',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesOpretRoute = ActivitiesOpretRouteImport.update({
  id: '/activities/opret',
  path: '/activities/opret',
  getParentRoute: () => rootRouteImport,
} as any)
const GodaddyUsersIndexRoute = GodaddyUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const GodaddyInterestsIndexRoute = GodaddyInterestsIndexRouteImport.update({
  id: '/interests/',
  path: '/interests/',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const ActivitiesSlugIndexRoute = ActivitiesSlugIndexRouteImport.update({
  id: '/activities/$slug/',
  path: '/activities/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GodaddyUsersGenerateRoute = GodaddyUsersGenerateRouteImport.update({
  id: '/users/generate',
  path: '/users/generate',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const GodaddyUsersCreateRoute = GodaddyUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const GodaddyInterestsRelationsRoute =
  GodaddyInterestsRelationsRouteImport.update({
    id: '/interests/relations',
    path: '/interests/relations',
    getParentRoute: () => GodaddyRouteRoute,
  } as any)
const GodaddyInterestsGenerateRoute =
  GodaddyInterestsGenerateRouteImport.update({
    id: '/interests/generate',
    path: '/interests/generate',
    getParentRoute: () => GodaddyRouteRoute,
  } as any)
const GodaddyInterestsCreateRoute = GodaddyInterestsCreateRouteImport.update({
  id: '/interests/create',
  path: '/interests/create',
  getParentRoute: () => GodaddyRouteRoute,
} as any)
const ActivitiesSlugRedigerRoute = ActivitiesSlugRedigerRouteImport.update({
  id: '/activities/$slug/rediger',
  path: '/activities/$slug/rediger',
  getParentRoute: () => rootRouteImport,
} as any)
const GodaddyUsersUserIdEditRoute = GodaddyUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => GodaddyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/godaddy': typeof GodaddyRouteRouteWithChildren
  '/buddies': typeof BuddiesRoute
  '/complete': typeof CompleteRoute
  '/completed': typeof CompletedRoute
  '/confirmemail': typeof ConfirmemailRoute
  '/details': typeof DetailsRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile-edit': typeof ProfileEditRoute
  '/signup': typeof SignupRoute
  '/activities/opret': typeof ActivitiesOpretRoute
  '/api/generate-interests': typeof ApiGenerateInterestsRoute
  '/api/generate-relations': typeof ApiGenerateRelationsRoute
  '/api/generate-users': typeof ApiGenerateUsersRoute
  '/buddy/$slug': typeof BuddySlugRoute
  '/chat/$buddyId': typeof ChatBuddyIdRoute
  '/godaddy/analytics': typeof GodaddyAnalyticsRoute
  '/interesser/$slug': typeof InteresserSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/activities': typeof ActivitiesIndexRoute
  '/chat': typeof ChatIndexRoute
  '/godaddy/': typeof GodaddyIndexRoute
  '/interesser': typeof InteresserIndexRoute
  '/activities/$slug/rediger': typeof ActivitiesSlugRedigerRoute
  '/godaddy/interests/create': typeof GodaddyInterestsCreateRoute
  '/godaddy/interests/generate': typeof GodaddyInterestsGenerateRoute
  '/godaddy/interests/relations': typeof GodaddyInterestsRelationsRoute
  '/godaddy/users/create': typeof GodaddyUsersCreateRoute
  '/godaddy/users/generate': typeof GodaddyUsersGenerateRoute
  '/activities/$slug': typeof ActivitiesSlugIndexRoute
  '/godaddy/interests': typeof GodaddyInterestsIndexRoute
  '/godaddy/users': typeof GodaddyUsersIndexRoute
  '/godaddy/users/$userId/edit': typeof GodaddyUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buddies': typeof BuddiesRoute
  '/complete': typeof CompleteRoute
  '/completed': typeof CompletedRoute
  '/confirmemail': typeof ConfirmemailRoute
  '/details': typeof DetailsRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile-edit': typeof ProfileEditRoute
  '/signup': typeof SignupRoute
  '/activities/opret': typeof ActivitiesOpretRoute
  '/api/generate-interests': typeof ApiGenerateInterestsRoute
  '/api/generate-relations': typeof ApiGenerateRelationsRoute
  '/api/generate-users': typeof ApiGenerateUsersRoute
  '/buddy/$slug': typeof BuddySlugRoute
  '/chat/$buddyId': typeof ChatBuddyIdRoute
  '/godaddy/analytics': typeof GodaddyAnalyticsRoute
  '/interesser/$slug': typeof InteresserSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/activities': typeof ActivitiesIndexRoute
  '/chat': typeof ChatIndexRoute
  '/godaddy': typeof GodaddyIndexRoute
  '/interesser': typeof InteresserIndexRoute
  '/activities/$slug/rediger': typeof ActivitiesSlugRedigerRoute
  '/godaddy/interests/create': typeof GodaddyInterestsCreateRoute
  '/godaddy/interests/generate': typeof GodaddyInterestsGenerateRoute
  '/godaddy/interests/relations': typeof GodaddyInterestsRelationsRoute
  '/godaddy/users/create': typeof GodaddyUsersCreateRoute
  '/godaddy/users/generate': typeof GodaddyUsersGenerateRoute
  '/activities/$slug': typeof ActivitiesSlugIndexRoute
  '/godaddy/interests': typeof GodaddyInterestsIndexRoute
  '/godaddy/users': typeof GodaddyUsersIndexRoute
  '/godaddy/users/$userId/edit': typeof GodaddyUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/godaddy': typeof GodaddyRouteRouteWithChildren
  '/buddies': typeof BuddiesRoute
  '/complete': typeof CompleteRoute
  '/completed': typeof CompletedRoute
  '/confirmemail': typeof ConfirmemailRoute
  '/details': typeof DetailsRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile-edit': typeof ProfileEditRoute
  '/signup': typeof SignupRoute
  '/activities/opret': typeof ActivitiesOpretRoute
  '/api/generate-interests': typeof ApiGenerateInterestsRoute
  '/api/generate-relations': typeof ApiGenerateRelationsRoute
  '/api/generate-users': typeof ApiGenerateUsersRoute
  '/buddy/$slug': typeof BuddySlugRoute
  '/chat/$buddyId': typeof ChatBuddyIdRoute
  '/godaddy/analytics': typeof GodaddyAnalyticsRoute
  '/interesser/$slug': typeof InteresserSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/godaddy/': typeof GodaddyIndexRoute
  '/interesser/': typeof InteresserIndexRoute
  '/activities/$slug/rediger': typeof ActivitiesSlugRedigerRoute
  '/godaddy/interests/create': typeof GodaddyInterestsCreateRoute
  '/godaddy/interests/generate': typeof GodaddyInterestsGenerateRoute
  '/godaddy/interests/relations': typeof GodaddyInterestsRelationsRoute
  '/godaddy/users/create': typeof GodaddyUsersCreateRoute
  '/godaddy/users/generate': typeof GodaddyUsersGenerateRoute
  '/activities/$slug/': typeof ActivitiesSlugIndexRoute
  '/godaddy/interests/': typeof GodaddyInterestsIndexRoute
  '/godaddy/users/': typeof GodaddyUsersIndexRoute
  '/godaddy/users/$userId/edit': typeof GodaddyUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/godaddy'
    | '/buddies'
    | '/complete'
    | '/completed'
    | '/confirmemail'
    | '/details'
    | '/feed'
    | '/home'
    | '/interests'
    | '/location'
    | '/login'
    | '/profile'
    | '/profile-edit'
    | '/signup'
    | '/activities/opret'
    | '/api/generate-interests'
    | '/api/generate-relations'
    | '/api/generate-users'
    | '/buddy/$slug'
    | '/chat/$buddyId'
    | '/godaddy/analytics'
    | '/interesser/$slug'
    | '/strava/callback'
    | '/activities'
    | '/chat'
    | '/godaddy/'
    | '/interesser'
    | '/activities/$slug/rediger'
    | '/godaddy/interests/create'
    | '/godaddy/interests/generate'
    | '/godaddy/interests/relations'
    | '/godaddy/users/create'
    | '/godaddy/users/generate'
    | '/activities/$slug'
    | '/godaddy/interests'
    | '/godaddy/users'
    | '/godaddy/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buddies'
    | '/complete'
    | '/completed'
    | '/confirmemail'
    | '/details'
    | '/feed'
    | '/home'
    | '/interests'
    | '/location'
    | '/login'
    | '/profile'
    | '/profile-edit'
    | '/signup'
    | '/activities/opret'
    | '/api/generate-interests'
    | '/api/generate-relations'
    | '/api/generate-users'
    | '/buddy/$slug'
    | '/chat/$buddyId'
    | '/godaddy/analytics'
    | '/interesser/$slug'
    | '/strava/callback'
    | '/activities'
    | '/chat'
    | '/godaddy'
    | '/interesser'
    | '/activities/$slug/rediger'
    | '/godaddy/interests/create'
    | '/godaddy/interests/generate'
    | '/godaddy/interests/relations'
    | '/godaddy/users/create'
    | '/godaddy/users/generate'
    | '/activities/$slug'
    | '/godaddy/interests'
    | '/godaddy/users'
    | '/godaddy/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/godaddy'
    | '/buddies'
    | '/complete'
    | '/completed'
    | '/confirmemail'
    | '/details'
    | '/feed'
    | '/home'
    | '/interests'
    | '/location'
    | '/login'
    | '/profile'
    | '/profile-edit'
    | '/signup'
    | '/activities/opret'
    | '/api/generate-interests'
    | '/api/generate-relations'
    | '/api/generate-users'
    | '/buddy/$slug'
    | '/chat/$buddyId'
    | '/godaddy/analytics'
    | '/interesser/$slug'
    | '/strava/callback'
    | '/activities/'
    | '/chat/'
    | '/godaddy/'
    | '/interesser/'
    | '/activities/$slug/rediger'
    | '/godaddy/interests/create'
    | '/godaddy/interests/generate'
    | '/godaddy/interests/relations'
    | '/godaddy/users/create'
    | '/godaddy/users/generate'
    | '/activities/$slug/'
    | '/godaddy/interests/'
    | '/godaddy/users/'
    | '/godaddy/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GodaddyRouteRoute: typeof GodaddyRouteRouteWithChildren
  BuddiesRoute: typeof BuddiesRoute
  CompleteRoute: typeof CompleteRoute
  CompletedRoute: typeof CompletedRoute
  ConfirmemailRoute: typeof ConfirmemailRoute
  DetailsRoute: typeof DetailsRoute
  FeedRoute: typeof FeedRoute
  HomeRoute: typeof HomeRoute
  InterestsRoute: typeof InterestsRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProfileEditRoute: typeof ProfileEditRoute
  SignupRoute: typeof SignupRoute
  ActivitiesOpretRoute: typeof ActivitiesOpretRoute
  ApiGenerateInterestsRoute: typeof ApiGenerateInterestsRoute
  ApiGenerateRelationsRoute: typeof ApiGenerateRelationsRoute
  ApiGenerateUsersRoute: typeof ApiGenerateUsersRoute
  BuddySlugRoute: typeof BuddySlugRoute
  ChatBuddyIdRoute: typeof ChatBuddyIdRoute
  InteresserSlugRoute: typeof InteresserSlugRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  InteresserIndexRoute: typeof InteresserIndexRoute
  ActivitiesSlugRedigerRoute: typeof ActivitiesSlugRedigerRoute
  ActivitiesSlugIndexRoute: typeof ActivitiesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-edit': {
      id: '/profile-edit'
      path: '/profile-edit'
      fullPath: '/profile-edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmemail': {
      id: '/confirmemail'
      path: '/confirmemail'
      fullPath: '/confirmemail'
      preLoaderRoute: typeof ConfirmemailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddies': {
      id: '/buddies'
      path: '/buddies'
      fullPath: '/buddies'
      preLoaderRoute: typeof BuddiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godaddy': {
      id: '/godaddy'
      path: '/godaddy'
      fullPath: '/godaddy'
      preLoaderRoute: typeof GodaddyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesser/': {
      id: '/interesser/'
      path: '/interesser'
      fullPath: '/interesser'
      preLoaderRoute: typeof InteresserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godaddy/': {
      id: '/godaddy/'
      path: '/'
      fullPath: '/godaddy/'
      preLoaderRoute: typeof GodaddyIndexRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesser/$slug': {
      id: '/interesser/$slug'
      path: '/interesser/$slug'
      fullPath: '/interesser/$slug'
      preLoaderRoute: typeof InteresserSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godaddy/analytics': {
      id: '/godaddy/analytics'
      path: '/analytics'
      fullPath: '/godaddy/analytics'
      preLoaderRoute: typeof GodaddyAnalyticsRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/chat/$buddyId': {
      id: '/chat/$buddyId'
      path: '/chat/$buddyId'
      fullPath: '/chat/$buddyId'
      preLoaderRoute: typeof ChatBuddyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy/$slug': {
      id: '/buddy/$slug'
      path: '/buddy/$slug'
      fullPath: '/buddy/$slug'
      preLoaderRoute: typeof BuddySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-users': {
      id: '/api/generate-users'
      path: '/api/generate-users'
      fullPath: '/api/generate-users'
      preLoaderRoute: typeof ApiGenerateUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-relations': {
      id: '/api/generate-relations'
      path: '/api/generate-relations'
      fullPath: '/api/generate-relations'
      preLoaderRoute: typeof ApiGenerateRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-interests': {
      id: '/api/generate-interests'
      path: '/api/generate-interests'
      fullPath: '/api/generate-interests'
      preLoaderRoute: typeof ApiGenerateInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/opret': {
      id: '/activities/opret'
      path: '/activities/opret'
      fullPath: '/activities/opret'
      preLoaderRoute: typeof ActivitiesOpretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godaddy/users/': {
      id: '/godaddy/users/'
      path: '/users'
      fullPath: '/godaddy/users'
      preLoaderRoute: typeof GodaddyUsersIndexRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/godaddy/interests/': {
      id: '/godaddy/interests/'
      path: '/interests'
      fullPath: '/godaddy/interests'
      preLoaderRoute: typeof GodaddyInterestsIndexRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/activities/$slug/': {
      id: '/activities/$slug/'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godaddy/users/generate': {
      id: '/godaddy/users/generate'
      path: '/users/generate'
      fullPath: '/godaddy/users/generate'
      preLoaderRoute: typeof GodaddyUsersGenerateRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/godaddy/users/create': {
      id: '/godaddy/users/create'
      path: '/users/create'
      fullPath: '/godaddy/users/create'
      preLoaderRoute: typeof GodaddyUsersCreateRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/godaddy/interests/relations': {
      id: '/godaddy/interests/relations'
      path: '/interests/relations'
      fullPath: '/godaddy/interests/relations'
      preLoaderRoute: typeof GodaddyInterestsRelationsRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/godaddy/interests/generate': {
      id: '/godaddy/interests/generate'
      path: '/interests/generate'
      fullPath: '/godaddy/interests/generate'
      preLoaderRoute: typeof GodaddyInterestsGenerateRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/godaddy/interests/create': {
      id: '/godaddy/interests/create'
      path: '/interests/create'
      fullPath: '/godaddy/interests/create'
      preLoaderRoute: typeof GodaddyInterestsCreateRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
    '/activities/$slug/rediger': {
      id: '/activities/$slug/rediger'
      path: '/activities/$slug/rediger'
      fullPath: '/activities/$slug/rediger'
      preLoaderRoute: typeof ActivitiesSlugRedigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godaddy/users/$userId/edit': {
      id: '/godaddy/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/godaddy/users/$userId/edit'
      preLoaderRoute: typeof GodaddyUsersUserIdEditRouteImport
      parentRoute: typeof GodaddyRouteRoute
    }
  }
}

interface GodaddyRouteRouteChildren {
  GodaddyAnalyticsRoute: typeof GodaddyAnalyticsRoute
  GodaddyIndexRoute: typeof GodaddyIndexRoute
  GodaddyInterestsCreateRoute: typeof GodaddyInterestsCreateRoute
  GodaddyInterestsGenerateRoute: typeof GodaddyInterestsGenerateRoute
  GodaddyInterestsRelationsRoute: typeof GodaddyInterestsRelationsRoute
  GodaddyUsersCreateRoute: typeof GodaddyUsersCreateRoute
  GodaddyUsersGenerateRoute: typeof GodaddyUsersGenerateRoute
  GodaddyInterestsIndexRoute: typeof GodaddyInterestsIndexRoute
  GodaddyUsersIndexRoute: typeof GodaddyUsersIndexRoute
  GodaddyUsersUserIdEditRoute: typeof GodaddyUsersUserIdEditRoute
}

const GodaddyRouteRouteChildren: GodaddyRouteRouteChildren = {
  GodaddyAnalyticsRoute: GodaddyAnalyticsRoute,
  GodaddyIndexRoute: GodaddyIndexRoute,
  GodaddyInterestsCreateRoute: GodaddyInterestsCreateRoute,
  GodaddyInterestsGenerateRoute: GodaddyInterestsGenerateRoute,
  GodaddyInterestsRelationsRoute: GodaddyInterestsRelationsRoute,
  GodaddyUsersCreateRoute: GodaddyUsersCreateRoute,
  GodaddyUsersGenerateRoute: GodaddyUsersGenerateRoute,
  GodaddyInterestsIndexRoute: GodaddyInterestsIndexRoute,
  GodaddyUsersIndexRoute: GodaddyUsersIndexRoute,
  GodaddyUsersUserIdEditRoute: GodaddyUsersUserIdEditRoute,
}

const GodaddyRouteRouteWithChildren = GodaddyRouteRoute._addFileChildren(
  GodaddyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GodaddyRouteRoute: GodaddyRouteRouteWithChildren,
  BuddiesRoute: BuddiesRoute,
  CompleteRoute: CompleteRoute,
  CompletedRoute: CompletedRoute,
  ConfirmemailRoute: ConfirmemailRoute,
  DetailsRoute: DetailsRoute,
  FeedRoute: FeedRoute,
  HomeRoute: HomeRoute,
  InterestsRoute: InterestsRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProfileEditRoute: ProfileEditRoute,
  SignupRoute: SignupRoute,
  ActivitiesOpretRoute: ActivitiesOpretRoute,
  ApiGenerateInterestsRoute: ApiGenerateInterestsRoute,
  ApiGenerateRelationsRoute: ApiGenerateRelationsRoute,
  ApiGenerateUsersRoute: ApiGenerateUsersRoute,
  BuddySlugRoute: BuddySlugRoute,
  ChatBuddyIdRoute: ChatBuddyIdRoute,
  InteresserSlugRoute: InteresserSlugRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  InteresserIndexRoute: InteresserIndexRoute,
  ActivitiesSlugRedigerRoute: ActivitiesSlugRedigerRoute,
  ActivitiesSlugIndexRoute: ActivitiesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
