// AUTO-GENERATED by scripts/generate-interest-icons.py — do not edit by hand.
import type { ReactNode } from "react";

export const INTEREST_ICON_PATHS: Record<string, ReactNode> = {
  'badminton': (
    <><circle cx="8" cy="16" r="2"/><path d="M9.5 14.5l6-6"/><path d="M14 8l3-3 3 3-3 3"/><path d="M12 10l2 2M14 7l3 3M18 5l2 2"/></>
  ),
  'table-tennis': (
    <><circle cx="9" cy="9" r="4.5"/><path d="M12.5 12.5l4.5 4.5 2-2-4.5-4.5"/><circle cx="18.5" cy="6" r="1"/></>
  ),
  'bowling': (
    <><path d="M12 3c2 0 3 2 3 5s-1 4-1 6 1 3 1 5c0 1.5-1.3 2-3 2s-3-.5-3-2c0-2 1-3 1-5s-1-3-1-6 1-5 3-5z"/><circle cx="12" cy="7" r=".6" fill="currentColor"/></>
  ),
  'archery': (
    <><circle cx="10" cy="12" r="7"/><circle cx="10" cy="12" r="4"/><circle cx="10" cy="12" r="1.2"/><path d="M13 9l8-5"/><path d="M19 4l2 2M21 6l-2 2"/></>
  ),
  'crossfit': (
    <><path d="M9 6a3 3 0 0 1 6 0"/><path d="M8 6h8l1.5 3c.6 2 .2 5-1.5 7-1 1.2-2.5 2-4 2s-3-.8-4-2c-1.7-2-2.1-5-1.5-7z"/></>
  ),
  'biking': (
    <><circle cx="6" cy="16" r="4"/><circle cx="18" cy="16" r="4"/><path d="M6 16l4-8h5l3 8"/><path d="M10 8h-2"/><path d="M15 8l-1-3h-2"/></>
  ),
  'diving': (
    <><path d="M4 10h12a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2h-3l-1-2h-4l-1 2H4a2 2 0 0 1-2-2v-2a2 2 0 0 1 2-2z"/><path d="M18 13h2a2 2 0 0 1 2 2v0a2 2 0 0 1-2 2"/></>
  ),
  'fencing': (
    <><path d="M4 20l8-8"/><path d="M20 20l-8-8"/><path d="M3 17l3 3"/><path d="M21 17l-3 3"/><path d="M12 12l2-8"/><path d="M13 4h2"/></>
  ),
  'fishing': (
    <><path d="M3 12c3-5 8-6 13-6l4 6-4 6c-5 0-10-1-13-6z"/><circle cx="16" cy="11" r=".6" fill="currentColor"/><path d="M3 12l-2-2M3 12l-2 2"/></>
  ),
  'workout': (
    <><path d="M4 9v6M2 11v2"/><path d="M20 9v6M22 11v2"/><path d="M6 8v8M18 8v8"/><path d="M6 12h12"/></>
  ),
  'football': (
    <><circle cx="12" cy="12" r="9"/><path d="M12 6l4 3-1.5 5h-5L8 9z"/><path d="M12 6V3M14.5 14l2.5 2M9.5 14l-2.5 2M8 9L5 7.5M16 9l3-1.5"/></>
  ),
  'golf': (
    <><path d="M7 21V4"/><path d="M7 4l10 3-10 3"/><circle cx="7" cy="21" r="1"/></>
  ),
  'gravel-cycling': (
    <><circle cx="6" cy="16" r="4"/><circle cx="18" cy="16" r="4"/><path d="M6 16l4-8h5l3 8"/><path d="M10 8h-2"/><path d="M15 8l-1-3h-2"/><path d="M2 16h1M9 13l.5.5M15 13l.5.5M21 16h1"/></>
  ),
  'handball': (
    <><circle cx="12" cy="12" r="8"/><path d="M4.5 10.5l7 1.5 7-1.5"/><path d="M12 4v16"/><path d="M7 6.5l5 5.5 5-5.5"/></>
  ),
  'hockey': (
    <><path d="M4 5l12 12"/><path d="M16 17l4 2"/><ellipse cx="7" cy="20" rx="3" ry="1"/></>
  ),
  'kayaking': (
    <><path d="M3 15c3 3 15 3 18 0"/><path d="M6 14l2-2h8l2 2"/><path d="M2 9l6 2M22 9l-6 2"/><circle cx="12" cy="11" r=".8" fill="currentColor"/></>
  ),
  'martial-arts': (
    <><path d="M3 12h18"/><path d="M3 15h18"/><path d="M9 12v3M15 12v3"/><path d="M9 10c0-3 2-5 3-5s3 2 3 5"/><path d="M10 15l-1 4h6l-1-4"/></>
  ),
  'canoeing': (
    <><path d="M3 13c3 3 15 3 18 0"/><path d="M5 13l2-2h10l2 2"/><path d="M9 11V7M15 11V7"/></>
  ),
  'kitesurfing': (
    <><path d="M5 4l4 5-4 3z"/><path d="M7 9l4 9"/><path d="M9 20h8"/></>
  ),
  'climbing': (
    <><path d="M3 20l6-10 4 6 3-4 5 8z"/><circle cx="13" cy="6" r="1.5"/><path d="M13 8v4"/><path d="M11 10l4-1"/></>
  ),
  'croquet-golf': (
    <><path d="M4 18h16"/><path d="M12 18V7"/><rect x="7" y="3" width="10" height="4" rx="1"/></>
  ),
  'cross-country-skiing': (
    <><circle cx="13" cy="4" r="1.5"/><path d="M12 7l-1 5 2 3-1 4"/><path d="M14 10l2 2 3-1"/><path d="M5 19l14-3"/><path d="M7 21l14-3"/></>
  ),
  'running': (
    <><circle cx="14" cy="4" r="1.5"/><path d="M13 7l-2 4 3 2v4"/><path d="M14 13l3-1 2 2"/><path d="M11 11l-3 1-1 3"/></>
  ),
  'mountain-biking': (
    <><path d="M2 17l4-5 3 3 3-4 5 6"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/><path d="M9 12h3l2 4"/></>
  ),
  'backcountry-skiing': (
    <><path d="M3 20l18-6"/><circle cx="14" cy="5" r="1.5"/><path d="M13 8l-1 4 2 2-1 3"/><path d="M15 10l3 1 2-2"/></>
  ),
  'padel-tennis': (
    <><ellipse cx="10" cy="9" rx="5" ry="6"/><circle cx="8" cy="8" r=".5" fill="currentColor"/><circle cx="11" cy="7" r=".5" fill="currentColor"/><circle cx="9" cy="11" r=".5" fill="currentColor"/><circle cx="12" cy="10" r=".5" fill="currentColor"/><path d="M13 13l6 6"/></>
  ),
  'petanque': (
    <><circle cx="8" cy="14" r="3"/><circle cx="16" cy="14" r="3"/><circle cx="12" cy="9" r="2"/><circle cx="12" cy="18" r=".6" fill="currentColor"/></>
  ),
  'horseback-riding': (
    <><path d="M7 20v-4c0-4 2-7 6-7h2l3-3 1 3-2 2v4c0 2-1 5-4 5"/><path d="M11 9V6l2-2"/><circle cx="15" cy="12" r=".6" fill="currentColor"/></>
  ),
  'rowing': (
    <><path d="M3 14c3 3 15 3 18 0"/><path d="M11 12l2-2 2 2"/><path d="M4 11l6 2M20 11l-6 2"/></>
  ),
  'inline-skating': (
    <><path d="M5 10h12l-1 4h-10z"/><path d="M17 7v3"/><circle cx="7" cy="17" r="1.5"/><circle cx="11" cy="17" r="1.5"/><circle cx="15" cy="17" r="1.5"/><path d="M6 14v1M16 14v1"/></>
  ),
  'sailing': (
    <><path d="M12 3v14"/><path d="M12 5l6 12h-6z"/><path d="M3 17c3 3 15 3 18 0"/></>
  ),
  'skateboarding': (
    <><path d="M3 12h18l-1 3H4z"/><circle cx="7" cy="17" r="1.5"/><circle cx="17" cy="17" r="1.5"/></>
  ),
  'skiing': (
    <><path d="M7 3l-2 16"/><path d="M17 3l2 16"/><path d="M9 5l8 10"/><path d="M4 20l16 0"/></>
  ),
  'ice-skating': (
    <><path d="M6 6c3 0 4 2 4 4v4l3 2h4"/><path d="M4 17h16"/><path d="M4 20h16"/></>
  ),
  'snowboard': (
    <><rect x="3" y="9" width="18" height="6" rx="3" transform="rotate(-10 12 12)"/><path d="M9 11v2M15 11v2"/></>
  ),
  'squash': (
    <><ellipse cx="9" cy="9" rx="5" ry="6"/><path d="M13 13l6 6"/><path d="M7 7l4 4M11 7l-4 4"/></>
  ),
  'stand-up-paddle': (
    <><path d="M3 17c3 3 15 3 18 0"/><ellipse cx="12" cy="15" rx="7" ry="1.3"/><path d="M16 14V4"/><path d="M14 5h4"/></>
  ),
  'weight-training': (
    <><path d="M3 9v6M5 7v10"/><path d="M21 9v6M19 7v10"/><path d="M5 12h14"/></>
  ),
  'surfing': (
    <><path d="M12 3c2 4 2 12 0 16-4-2-6-6-6-8s2-6 6-8z"/><path d="M3 20c2 1 4 1 6 0s4-1 6 0 4 1 6 0"/></>
  ),
  'swimming': (
    <><circle cx="8" cy="6" r="1.5"/><path d="M10 8l3 1 3-2 3 3"/><path d="M3 14c2 2 4 2 6 0s4-2 6 0 4 2 6 0"/><path d="M3 18c2 2 4 2 6 0s4-2 6 0 4 2 6 0"/></>
  ),
  'tennis': (
    <><circle cx="9" cy="9" r="5"/><path d="M6 6l6 6M12 6l-6 6"/><path d="M13 13l6 6"/><circle cx="19" cy="6" r="1.2"/></>
  ),
  'triathlon': (
    <><circle cx="5" cy="16" r="2.5"/><path d="M8 8c1 1 2 1 3 0s2-1 3 0"/><circle cx="18" cy="16" r="2.5"/><path d="M8 16h7"/><path d="M12 8l1 4"/></>
  ),
  'hiking': (
    <><path d="M4 18V8h4v4l6 2 3 1 3 3H4z"/><path d="M4 18h16"/><path d="M8 8h2"/></>
  ),
  'windsurfing': (
    <><path d="M3 19c3 2 15 2 18 0"/><path d="M8 17l6-14 4 14z"/><path d="M8 17l10 0"/></>
  ),
  'yoga': (
    <><circle cx="12" cy="6" r="2"/><path d="M12 8v4"/><path d="M7 18c1-4 4-6 5-6s4 2 5 6z"/><path d="M5 19h14"/></>
  ),
};
