-- Set interests.icon to a kebab-case English identifier matching
-- /public/icons/interests/{icon}.svg (and the INTEREST_ICON_PATHS map
-- used by <InterestIcon/> for inline SVG rendering with currentColor).
UPDATE public.interests SET icon = CASE slug
  WHEN 'badminton'        THEN 'badminton'
  WHEN 'bordtennis'       THEN 'table-tennis'
  WHEN 'bowling'          THEN 'bowling'
  WHEN 'bueskydning'      THEN 'archery'
  WHEN 'crossfit'         THEN 'crossfit'
  WHEN 'cykling'          THEN 'biking'
  WHEN 'dykning'          THEN 'diving'
  WHEN 'faegtning'        THEN 'fencing'
  WHEN 'fiskeri'          THEN 'fishing'
  WHEN 'fitness'          THEN 'workout'
  WHEN 'fodbold'          THEN 'football'
  WHEN 'golf'             THEN 'golf'
  WHEN 'gravelcykling'    THEN 'gravel-cycling'
  WHEN 'haandbold'        THEN 'handball'
  WHEN 'hockey'           THEN 'hockey'
  WHEN 'kajakroning'      THEN 'kayaking'
  WHEN 'kampsport'        THEN 'martial-arts'
  WHEN 'kano'             THEN 'canoeing'
  WHEN 'kitesurfing'      THEN 'kitesurfing'
  WHEN 'klatring'         THEN 'climbing'
  WHEN 'krolf'            THEN 'croquet-golf'
  WHEN 'langrend'         THEN 'cross-country-skiing'
  WHEN 'loeb'             THEN 'running'
  WHEN 'mountainbiking'   THEN 'mountain-biking'
  WHEN 'off-piste-skilob' THEN 'backcountry-skiing'
  WHEN 'padel-tennis'     THEN 'padel-tennis'
  WHEN 'petanque'         THEN 'petanque'
  WHEN 'ridning'          THEN 'horseback-riding'
  WHEN 'roning'           THEN 'rowing'
  WHEN 'rulleskojtlob'    THEN 'inline-skating'
  WHEN 'sejlads'          THEN 'sailing'
  WHEN 'skateboarding'    THEN 'skateboarding'
  WHEN 'skiloeb'          THEN 'skiing'
  WHEN 'skojtlob'         THEN 'ice-skating'
  WHEN 'snowboard'        THEN 'snowboard'
  WHEN 'squash'           THEN 'squash'
  WHEN 'stand-up-paddle'  THEN 'stand-up-paddle'
  WHEN 'styrketraening'   THEN 'weight-training'
  WHEN 'surfing'          THEN 'surfing'
  WHEN 'svoemning'        THEN 'swimming'
  WHEN 'tennis'           THEN 'tennis'
  WHEN 'triatlon'         THEN 'triathlon'
  WHEN 'vandring'         THEN 'hiking'
  WHEN 'windsurfing'      THEN 'windsurfing'
  WHEN 'yoga'             THEN 'yoga'
  ELSE icon
END
WHERE slug IS NOT NULL;

